---
###################
# User/Profile info
###################
PROFILE:
  ## git informations
  email:    ''
  realname: ''

  ## default shell
  shell:    '/bin/zsh'

  ## zsh shell layout [grml,prezto,ohmyzsh]
  zshShell: 'grml'

  ## automatic ssh key fetching from github
  #githubUser: 'example'


###################
# Provisioning features
###################
PROVISION:
  update:      1      # do full system update for each full provisoning
  samba:       1      # Samba server
  ntp:         1      # Time synchronization
  mail:        1      # Mail sandbox
  php:         1      # Local PHP
  dnsmasq:     1      # dnsmasq service (needed for docker consul registration)
  consul:      1      # Docker consul service
  docker:      1      # Docker server
  dockerDory:  1      # Docker docker service --> https://github.com/FreedomBen/dory
  clitools:    1      # CliTools
  desktop:     0      # GUI desktop [0, kde, unity, gnome]
  manpages:    1      # Manpages are not available in baseimage, so reinstall them
  buildEssentials: 0  # build essentials (gcc, compilers...)

  ## Filesystem of data disk [ext3,ext4,xfs,btrfs]
  dataFS: 'ext4'

###################
# VM SETTINGS
###################
VM:
  ## Development domain (automatic redirect of *.vm for internal use)
  developmentDomain: 'vm'

  ## Insecure registry for Docker
  #dockerRegistry: ''

  ## Additional docker opts
  ##  -> if you use btrfs you can set: -s btrfs
  dockerOpts: ''

  ## Password for growl server
  growlPassword: ''
