- name: Install default provisioning packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - parted
    - curl

- name: Install default tool packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - zsh
    - moreutils
    - byobu
    - multitail
    - dnsutils
    - telnet
    - vim
    - tmux

- name: Install default compression packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - zip
    - unzip
    - bzip2
    - p7zip-full

- name: Install default development packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - git
    - sudo
    - cstream

- name: Install default other packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - incron
