- name: Install developer packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    # Tools
    - jq
    - sloccount
    - pydf
    - ack-grep
    - tig
    # Status tools
    - htop
    - atop
    - iftop
    - mytop
    - iotop
    - pfqueue
    # System
    - fuse
    - sshfs
    - xvfb
    # ldap
    - ldap-utils
    # Compiling/Debugging
    - build-essential
    - strace
    - closure-compiler
    - g++
    # Network
    - tshark
    - tcpflow
    - tcpdump
    - ngrep
    - swaks
    - ethtool
    - netcat-openbsd
    - mailutils
    - mysql-client
    # Dev stuff
    - libsqlite3-dev
    - php5-dev
    - libcurl3-gnutls-dev
    - libxml2-dev
    - libxml2-utils
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    # Other stuff
    - tnef
    - dos2unix
    - octave
    - lynx
    - links
    - mutt
    - p7zip
    - unrar
    - unace
    - colordiff
    - graphviz
    # Languages
    - ruby
    - ruby-dev
    - ruby-compass
    # VCS
    - subversion
    - git
    - git-flow
    # Conversion tools
    - poppler-utils
    - graphicsmagick
    - imagemagick
    - wkhtmltopdf
