- name: Install developer tool packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - jq
    - sloccount
    - pydf
    - ack-grep
    - tig

- name: Install developer status packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - htop
    - atop
    - iftop
    - mytop
    - iotop
    - pfqueue

- name: Install developer system packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - fuse
    - sshfs
    - xvfb

- name: Install developer ldap packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - ldap-utils

- name: Install developer compiling packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - build-essential
    - strace
    - closure-compiler
    - g++

- name: Install developer network packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - tshark
    - tcpflow
    - tcpdump
    - ngrep
    - swaks
    - ethtool
    - netcat-openbsd
    - mailutils
    - mysql-client

- name: Install developer library packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - libsqlite3-dev
    - php5-dev
    - libcurl3-gnutls-dev
    - libxml2-dev
    - libxml2-utils
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev

- name: Install developer language packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - ruby
    - ruby-dev
    - ruby-compass

- name: Install developer vcs packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - subversion
    - git
    - git-flow

- name: Install developer conversion tool packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - poppler-utils
    - graphicsmagick
    - imagemagick
    - wkhtmltopdf

- name: Install developer other packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - tnef
    - dos2unix
    - octave
    - lynx
    - links
    - mutt
    - p7zip
    - unrar
    - unace
    - colordiff
    - graphviz