- name: Install developer packages
  action: apt pkg='{{ item }}' state=latest
  when: ansible_distribution == 'Ubuntu'
  with_items:
    # Tools
    - jq
    # nodejs
    - nodejs
    - nodejs-legacy
    - node-less
    - npm

#- name: Update npm packages
#  command: 'npm update -g'

- name: Install npm packages
  npm: name='{{ item }}' global=yes state=latest production=yes
  with_items:
   # Tools
   - growl
   - bower
   - phantomjs
   - typescript
   - jshint
   - jslint
   # Grunt
   - grunt
   # Gulp
   - gulp
