- name: Deploy php configuration
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/php/files/
    dest: /etc/php5/
    delete: no

- name: Enable php modules/configurations
  command: 'php5enmod {{ item }}'
  with_items:
   - mcrypt
   - local-prod
   - local-dev