---

- name: Install php
  include: install.yml
  tags:
    - bootstrap

- name: Configure php
  include: configuration.yml
  tags:
    - bootstrap

- name: Install phars
  include: phar.yml
  tags:
    - bootstrap
