- name: Reload AppArmor
  command: 'service apparmor reload'

- name: Restart Docker
  command: '{{ item }}'
  with_items:
    - systemctl daemon-reload
    - systemctl enable docker
    - systemctl restart docker
