---

- name: Deploy dovecot configuration
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/mail/files/dovecot/
    dest: /etc/dovecot/
    delete: no

- name: Dovecot configuration
  lineinfile:
    dest:   /etc/dovecot/local.conf
    regexp: '^[\s#]*{{ item.variable }}[\s]*='
    line:   '{{ item.variable }}={{ item.value }}'
  with_items:
    - { variable: 'listen', value: '127.0.0.1 {{ VM.network.private.address }}' }
  notify:
    - Restart dovecot
