- name: Fetch clitools (latest)
  get_url:
    url:   'https://dl.webdevops.io/clicommand/clitools.phar'
    dest:  /usr/local/bin/ct
    owner: 'root'
    group: 'root'
    mode:  0755

- name: Install clitools additional packages
  action: apt pkg='{{ item }}' state=latest
  with_items:
    # Tools
    - git
    - wget
    - multitail
    - sudo
    - moreutils
    # Network
    - tshark
    - tcpflow
    - tcpdump
    - ngrep
    # Debug
    - strace
    - lsof
