- name: Deploy samba configuration
  synchronize:
    rsync_path: "sudo rsync"
    src: roles/samba/files/
    dest: /etc/samba/
    delete: no

- name: Creates code directory
  file:
    path: /mnt/code
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0775

- name: Init samba
  command: 'service {{ item }} restart'
  with_items:
    - nmbd
    - smbd
