---

- name: Install samba
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - samba

- name: Init samba
  raw: '{{ item }}'
  with_items:
    - (echo vagrant; echo vagrant) | smbpasswd -s -a vagrant

