---

- name: Install docker utils
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - curl
    - aufs-tools

- name: Install docker
  apt:
    pkg:   '{{ item }}'
    state: latest
  with_items:
    - docker-engine
