- name: Cleanup old orphaned docker images
  raw: 'docker rmi $(docker images -qf "dangling=true")'
  when: DOCKER.cleanup.images is defined and DOCKER.cleanup.images
  ignore_errors: yes

- name: Get newest cleanup docker container
  command: "docker pull martin/docker-cleanup-volumes"
  when: DOCKER.cleanup.volumes is defined and DOCKER.cleanup.volumes
  ignore_errors: yes

- name: Cleanup old orphaned docker volumes
  raw: 'docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes'
  when: DOCKER.cleanup.volumes is defined and DOCKER.cleanup.volumes
  ignore_errors: yes

- name: Cleanup old temp builds
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /var/lib/docker/tmp/*
  when: DOCKER.cleanup.tmp is defined and DOCKER.cleanup.tmp
  ignore_errors: yes
