- name: Install docker
  include: install.yml
  tags:
    - bootstrap

#- name: Maintenance docker
#  include: maintenance.yml
#  tags:
#    - bootstrap

- name: Configure docker
  include: configuration.yml
  tags:
    - bootstrap
