- name: Install recent kernel version
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - 'linux-image-generic-lts-vivid'
    - 'linux-image-extra-virtual-lts-vivid'
    - 'linux-lts-vivid-tools-common'
    - 'linux-headers-generic-lts-vivid'

# TODO: update guest tools?
# ansible_virtualization_type
