- name: Install custom specific kernel version
  include: install-version.yml
  when: PACKAGES.kernel != "recent"
  tags:
    - bootstrap

- name: Install custom recent kernel
  include: install-recent.yml
  when: PACKAGES.kernel == "recent"
  tags:
    - bootstrap
