- name: Unmount SDB1
  mount: name=/mnt/data src=/dev/sdb1 fstype=ext4 state=unmounted

- name: Remove mount SDB1
  mount: name=/mnt/data src=/dev/sdb1 fstype=ext4 state=absent

- name: Generate disk label (SDB)
  command: 'parted /dev/sdb mklabel gpt'

- name: Create partition (SDB)
  command: 'parted -- /dev/sdb mkpart primary 1M -1'

- name: Create filesystem (SDB)
  command: 'mkfs.ext4 /dev/sdb1'
