- name: Deploy dnsmasq configuration
  template:
    src:   roles/dnsmasq/templates/development.j2
    dest:  /etc/dnsmasq.d/development
    owner: vagrant
    group: root
    mode:  0644

- name: Restart dnsmasq
  command: service dnsmasq restart
